exdata2 <- exdata1[1:8]
library("dplyr")
exdata2 <- rename(exdata2, AMT_17 = Y17_AMT, AMT_17 = Y16_AMT)
View(exdata2)
exdata2 <- rename(exdata2, AMT17 = Y17_AMT)
exdata2 <- rename(exdata2, AMT16 = Y16_AMT)
m_history <- sample1 %>% filter(SEX == "M")
f_history <- sample1 %>% filter(SEX == "F")
library("writexl")
library("readxl")
jeju_y17_history <- read_excel("c:/rstudy/Sample4_y17_history.xlsx")
jeju_y16_history <- read_excel("c:/rstudy/Sample5_y16_history.xlsx")
bind_col <- left_join(jeju_y17_history, jeju_y16_history, by="ID")
bind_col_inner <- inner_join(jeju_y17_history, jeju_y16_history, by="ID")
bind_col_full <- full_join(jeju_y17_history, jeju_y16_history, by="ID")
x1 <- c(1,2,NA,4,5)
x1
x1*10
is.na(x1)
table(is.na(x1))
sum(x1)
sum(x1, na.rm = T)
install.packages("psych")
library(psych)
x1 = c(1,2,3,4,5,6,100,101)
mean(x1)
median(x1)
x2 = c(1,2,3,5,6,100)
median(x2)
max(x2)
min(x2)
range(x2)
quantile(x2)
quantile(x2, probs = 0.25)
quantile(x2, probs = 0.8)
var(x2)
sd(x2)
kurtosi(x2)
skew(x2)
exdata1<- read_excel("c:/rstudy/sample.xlsx")
install.packages("descr")
library(descr)
freq_test <- freq(exdata$AREA)
stem(exdata1$AGE)
barplot(exdata1$AGE)
hist(exdata1$AGE)
hist(exdata1$AGE, xlim = c(0,60), ylim = c(0,5))
freq(exdata1$SEX, main = "성별(barplot")
freq(exdata1$SEX, ylim = c(0, 10), main = "성별(barplot)")
barplot(table(exdata1$SEX), main = "성별")
table(exdata1$SEX)
dist_sex = table(exdata1$SEX)
barplot(dist_sex, ylim = c(0,8), main = "sex barplot", xlab = "SEX", ylab = "frequency",
        names = c("Female", "Male"), col = c("pink", "navy"))
boxplot(exdata1$Y17_CNT, exdata1$Y16_CNT)
boxplot(exdata1$Y17_CNT, exdata1$Y16_CNT, ylim = c(0, 60), main = "boxplot",
        names = c("17년건수","16년건수"), col = c("green","yellow"))
y1 = c(1,2,3,4,5,6,7,8,9,10,20,25)
boxplot(y1)
