library()
Sys.setlocale("LC_ALL", "English_United States.1252")
install.packages("extrafont")
library(extrafont)
font_import()
y
library(reshape2)
head(airquality)
names(airquality) <- tolower(names(airquality))
View(airquality)
melt_test <- melt(airquality)
head(melt_test)
tail(melt_test)
melt_test2 <- melt(airquality, id.vars = c("month","wind"), measure.vars = "ozone")
head(melt_test2)
aq_melt <- melt(airquality, id = c("month", "day"), na.rm = TRUE)

aq_dcast = dcast(aq_melt, month + day ~ variable)
View(aq_dcast)
View(aq_melt)
aq_acast1 = acast(aq_melt, day~month~variable)
aq_acast2 = acast(aq_melt, month ~ variable, mean)
View(aq_acast1)
View(aq_acast2)
