library(readxl)
han <- read_excel("c:/rstudy/한식집_가공.xlsx")
head(han)
cut_address <- substr(han$소재지전체주소,13,15)
head(cut_address)
no_num_addr <- gsub("[0-9]","", cut_address)
no_space_address <- gsub(" ", "", no_num_addr)
Done_address <- gsub("-","",no_space_address)
head(Done_address)
library(dplyr)
addr_count <- Done_address %>% table() %>% data.frame()
head(addr_count)
install.packages("treemap")
library(treemap)
treemap(addr_count, index = ".", vSize = "Freq", title = "팔달구 동별 한식집 분포")
arrange(addr_count, desc(Freq)) %>% head()

sort_addr <- arrange(addr_count, desc(Freq))
View(sort_addr)
