library(readxl)
library(dplyr)
dustdata <- read_excel("c:/rstudy/finedust.xlsx")
View(dustdata)
str(dustdata)
dustdata_compare <- dustdata %>% filter(area %in% c("구로구","금천구"))
View(dustdata_compare)
count(dustdata_compare, yyyymmdd) %>% arrange(desc(n))
count(dustdata_compare, area) %>% arrange(desc(n))
dust_area_goo <- subset(dustdata_compare, area =="구로구")
dust_area_gold <- subset(dustdata_compare, area =="금천구")
View(dust_area_goo)
View(dust_area_gold)
install.packages("psych")
library(psych)
describe(dust_area_goo$finedust)
describe(dust_area_gold$finedust)
boxplot(dust_area_goo$finedust, dust_area_gold$finedust,
        main = "finedust_compare", xlab = "AREA", ylab = "FINEDUST_PM", 
        names = c("구로구","금천구"), col = c("blue", "green"))
t.test(data = dustdata_compare, finedust ~ area, var.equal = T)
